parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: osoweb_bd
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 19809b2c15acc909d2081df9f411232a9502deae
    database_path: null
